import Head from "next/head";
import React from "react";
import HeadAbout from "../components/about/HeadAbout";
import Hero from "../components/about/Hero";
import Experience from "../components/experience/Experience";
import RecentProejct from "../components/recent-project/RecentProejct";
import Services from "../components/services/Services";
import Testimnial from "../components/Testimonial/Testimnial";

const about = () => {
  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* about title */}
      <HeadAbout title={"About Me"} breadcum={"About"} />
      {/* about hero */}
      <Hero />

      {/* Experience */}
      <Experience />

      {/* Recent Proejct */}
      <RecentProejct />

      {/* services */}
      <Services />

      {/* testimonial */}
      <Testimnial />
    </>
  );
};

export default about;
