import axios from 'axios';
import Head from "next/head";
import React, { useEffect, useState } from "react";
import HeadAbout from "../components/about/HeadAbout";
import PortfolioModal from "../components/Portfolio/PortfolioModal";
import PortfolioTabs from "../components/Portfolio/PortfolioTabs";


const Portfolio = () => {
  const [show, setShow] = useState(false);
  const [portfolioData, setPortfolioData] = useState([]);
  // const [data, setData] = useState(portfolioData);
  const [filterData, setFilterData] = useState(portfolioData);


  useEffect(() => {
    axios('/assets/data/portfolio.json')
    .then(response => {
    console.log(response.data)
    setPortfolioData(response.data);
    setFilterData(response.data);
    })
    .catch(error => {
    console.log('Error getting fake data: ' + error);
    })
    }, []);

  useEffect(() => {}, [filterData]);

  const getData = (item) => {
    console.log(item);
  };

  const handleFilter = (title) => {
    title === "All Projects"
      ? setFilterData(portfolioData)
      : setFilterData(portfolioData.filter((item) => item.category === title));
  };
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Head title */}
      <HeadAbout title={"Portfolio Work"} breadcum={"Portfolio"} />
      

      <div className="gallery-area pt-100 pb-70 portfolio">
        <div className="container">
          <h2>Showcasing some of my best work</h2>
          <div className="shorting-menu">
            {[
              "All Projects",
              "Development",
              "Website Design",
              "Mobile App Design"
            ].map((item, i) => (
              <button
                key={i}
                className="filter"
                onClick={() => handleFilter(item)}
                defaultChecked={() => handleFilter("All Projects")}
              >
                {item}
              </button>
            ))}
          </div>
          <div className="shorting">
            <div className="row">
              <PortfolioTabs
                setShow={setShow}
                show={show}
                data={filterData}
                getData={getData}
              />
            </div>
          </div>
        </div>
      </div>
      {/* <!-- Modal --> */}
      <PortfolioModal setShow={setShow} show={show} />
    </>
  );
};

export default Portfolio;
